### ISSUE TITLE
[MPI] Enable within interactive environment

### ISSUE THREAD

**Issue by no-ponomarev** [modin-project/unidist#139]
Enable Jupiter/Console interactive mode with MPI. Look at _Bodo_ project.

**Comment by YarShev** [comment]
We already allow to run Jupyter via our CLI as follows
```bash
unidist -b mpi -m jupyter lab
```
or
```bash
unidist -b mpi -m jupyter notebook
```

**Comment by YarShev** [comment]
As to python/ipython interactive mode, we could try to use `ipyparallel`.

**Comment by YarShev** [comment]
#144 allows to run unidist on MPI in ipython as

```bash
UNIDIST_BACKEND=mpi mpiexec -n 1 ipython
```

in jupyter as

```bash
UNIDIST_BACKEND=mpi mpiexec -n 1 jupyter lab/notebook
```
