### ISSUE TITLE
Rename python multiprocessing and sequential python backends

### ISSUE THREAD

**Issue by raphaelauv** [modin-project/unidist#248]
What about more explicit backends name ?

multiprocessing -> multiprocessing-python | mp-python
python -> sequential-python

**Comment by YarShev** [comment]
Hi @raphaelauv, thanks for your post. That is really good point. However, I was thinking on the following renaming.

```
`multiprocessing` -> `mp` or `mp-py`
`python` -> `py`
```

I don't think that having `multiprocessing-python` and `sequential-python` is good-looking for users as it requires them to spell out such long names. What do you think?

**Comment by raphaelauv** [comment]
👍 I agree with you , also I like explicit and short.

What about `mp-py` and `seq-py`

**Comment by YarShev** [comment]
I think `py-mp` (or even without a hyphen, just `pymp`) is a good name for python processing backend so let's keep it. Regarding sequential python backend, I am not sure about the prefix `seq` in `seq-py` name. Why do you think that just `py` is not enough?

**Comment by raphaelauv** [comment]
My proposition was to make things explicit for end users 

“Programs must be written for people to read, and only incidentally for machines to execute.”
― Harold Abelson,

**Comment by YarShev** [comment]
We will take into account your suggestion when making the renaming, thanks. I will keep this issue open till we do that.

**Comment by YarShev** [comment]
@raphaelauv, I renamed "multiprocessing" to "pymp" and "python" to "pyseq". The changes are already in master. Hope, that fits you.
