### ISSUE TITLE
there is a typo in mpi backend

### ISSUE THREAD

**Issue by luweizheng** [modin-project/unidist#303]
SMPD should be SPMD

![image](https://github.com/modin-project/unidist/assets/57242864/0c110096-7bdb-495d-8a21-2e4869130eb3)

**Comment by YarShev** [comment]
Hi @luweizheng, thanks for opening this issue. Would you like to go ahead and open a PR with a fix? Please look at https://unidist.readthedocs.io/en/latest/developer/contributing.html beforehand.
